FROM node:18.16.1

WORKDIR /src/services/orchestrator/

ENV PORT=4000

COPY package.json package-lock.json /src/services/orchestrator/

RUN npm install && npm cache clean --force

RUN npm install -g nodemon

COPY ./ ./

CMD ["npm", "run", "start"]